### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by tangabc** [Bareflank/hypervisor#79]
After successfully building the cross-compiler with 'setup-debian.sh', I tried to build the hypervisor with make, but the compilation failed. 

Would appreciate any help in fixing this compilation problem. Thanks!

========= [LOGS]

~/Research/hypervisor > uname -a
Linux desktop 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

~/Research/hypervisor > gcc --version
gcc (GCC) 5.3.0

~/Research/hypervisor> ./tools/scripts/setup-debian.sh
          ... (successful... truncated) ...
  cp -Rf /home/jamint/opt/cross/x86_64-elf/lib/libc++.so.1.0 /home/jamint/Research/hypervisor/bfvmm/bin/cross/libc++.so
  touch completed_install_libcxx
  set +x

~/Research/hypervisor> make
          ... (truncated) ...
/home/jamint/Research/hypervisor/bfvmm/src/vcpu/test
g++ .build/native/test.o .build/native/test_vcpu.o .build/native/test_vcpu_factory.o -o ../bin/native/test -L../bin/native -L../../vmxon/bin/native -L../../vmcs/bin/native -L../../debug_ring/bin/native -L../../intrinsics/bin/native -L../../exit_handler/bin/native -lvcpu -lvmxon -lvmcs -ldebug_ring -lintrinsics -lexit_handler
../../vmxon/bin/native/libvmxon.so: undefined reference to `memory_manager::instance()'
../bin/native/libvcpu.so: undefined reference to `serial_port_x86::~serial_port_x86()'
../bin/native/libvcpu.so: undefined reference to `serial_port_x86::serial_port_x86(unsigned char, unsigned int, unsigned char, PARITY_MODE, unsigned char)'
../bin/native/libvcpu.so: undefined reference to `serial_port_x86::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[4]: *** [../bin/native/test] Error 1
make[3]: *** [test] Error 2
make[2]: *** [vcpu] Error 2
make[1]: *** [src] Error 2
make: *** [bfvmm] Error 2

**Comment by rianquinn** [comment]
This is likely due to the fact that we use some C++14 features, and GCC is likely out-of-date in 14.04. Our Travis CI script has the commands to update GCC to 5.2 / 5.3. I'll setup a 14.04 VM and see if I can repro / fix the issue (likely take about a day to cleanup). While your waiting, feel free to try out the commands in the Travis CI script, or use 15.04. I'll post back what I find.

**Comment by tangabc** [comment]
Thanks!

In fact, the above issue still occurs after I upgraded my gcc to 5.3.0.

**Comment by rianquinn** [comment]
Ok, yeah I'll try to repro this. Likely I'll setup a brand new Ubuntu 14.04 VMWare VM, and give it a shot.

**Comment by tangabc** [comment]
Ok thanks. Feel free to holler if you need more information! Meanwhile I'll try this out on a fresh install of Debian 8, and post back.

**Comment by rianquinn** [comment]
The last time we tried on Debian, I know we had an issue compiling the driver entry. We are a couple of weeks from a "1.0" release so there are a couple of bugs that we are still working out. Our plan is once the last couple of features are complete, we plan to test on Debian, Cent OS, Fedora, Ubuntu etc... Windows and Multi-Core support are up next for our 1.1 release, and then we move onto Guest support (really basic guest support) for 2.0, which we hope to complete by the end of the year.

**Comment by rianquinn** [comment]
Ok, I tried it out on Ubuntu 14.04. I installed the VM using mini.iso, with no extra packages just to keep it simple. When I ran setup-debian.sh, it failed because c++14 was not supported. The result was, the script did not finish. I then used the Travis CI steps to setup the VM and update GCC and finished the script. Once I did that, the hypervisor built, and ran just fine. When you update GCC make sure you re-run the setup script so that it can finish, and then also make sure that GCC is in fact updated properly. Most instructions on the internet for GCC leave the original GCC in place, and add GCC 5.3 as a second compiler. In our case, you need to rm the old GCC symlinks and add new ones to the new GCC 5.3 (see Travis CI script). Give that a try and let me know if you have any issues. In the mean time, we will update the setup-debain.sh to run these same instructions so that this doesn't happen for other users.

**Comment by tangabc** [comment]
Thanks. Now the "make" and "make unittest" are working fine.

For the unittest though, I'm getting alot of non-zero exit codes, such as the following. The unittest does register no error:
totals: 426 passed, 0 failed

Is this expected?

------
start_vmm executed successfully:
    - exit code: 0


stop_vmm failed:
    - exit code: -30

stop_vmm: failed to execute symbol: -30
common_fini: failed to stop vmm
[ELF ALERT]: private_symbol_global [866] no such symbol: : register_eh_frame
load_vmm: failed to relocate the elf loader: -11010 - No such symbol (BFELF_ERROR_NO_SUCH_SYMBOL)

start_vmm failed:
    - exit code: -20

start_vmm: failed to execute start_vmm: -20
add_module: invalid arguments
add_module: invalid arguments
[ELF ALERT]: bfelf_file_init [615] invalid argument: fsize invalid
add_module: failed to initialize elf file: -11001 - Invalid argument (BFELF_ERROR_INVALID_ARG)
add_module: failed to add module. the vmm must be stopped, and unloaded prior to adding modules


[ELF ALERT]: private_symbol_global [866] no such symbol: : invalid_symbol
invalid_symbol could not be found: -11010 - No such symbol (BFELF_ERROR_NO_SUCH_SYMBOL)
[ELF ALERT]: private_symbol_global [866] no such symbol: : invalid_symbol
invalid_symbol could not be found: -11010 - No such symbol (BFELF_ERROR_NO_SUCH_SYMBOL)
execute_symbol: failed to resolve entry point: -11010

totals: 426 passed, 0 failed

**Comment by rianquinn** [comment]
Yes, that's expected. At some point, we probably should silence the errors :). But yeah, that's the unit tests making sure that the possible errors are being handled.

**Comment by rianquinn** [comment]
The following PR should fix the issue going forward. This provides a new script for Ubuntu that does the upgrade. 

https://github.com/Bareflank/hypervisor/pull/80
